platform :ios, '9.0'

inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'


def shared_pods()
# https://kotlinlang.org/docs/native-cocoapods.html#use-a-kotlin-gradle-project-as-a-cocoapods-dependency
  # Use it if Xcode run
  use_frameworks!
  # Use it if releaseIOSFramework
#  use_modular_headers!
  platform :ios, '13.5'

  pod 'sdkframework', :path => '../shared/sdkframework'
  pod 'MMKV', '2.2.1'
  pod 'CocoaLumberjack'
end

target 'iosApp' do
    shared_pods()
end